#!/usr/bin/env bash

input="$1"

if [[ ! -s "$input" ]]; then
  exit
fi

if [[ "$input" != *.jpg && "$input" != *.svg && "$input" != *.png ]]; then
  exit
fi

if [[ "$input" == usr/share/icons/* ]]; then
  exit
fi

input_size="$(stat -c '%s' "$input")"

if [[ "$input_size" -lt "$(( 4 * 1024 ))" ]]; then
  exit
fi

output=''

if [[ "$input" == *.png ]]; then
  output="$(mktemp --suffix=.png)"

  orig_colors=$(identify -format %k "$input")
  colors=$(awk "BEGIN {print int(${orig_colors}**0.4 * 5 )}" )

  convert "$input" -colors "${colors}" "$output"
  optipng -strip all -o3 "$output" 2>/dev/null
fi

if [[ "$input" = *.jpg ]]; then
  output="$(mktemp --suffix=.jpg)"

  jpegoptim --quiet --strip-all -m30 "$output" 2>/dev/null
fi

if [[ "$input" = *.svg ]]; then
  output="$(mktemp --suffix=.svg)"

  svgcleaner --remove-gradient-attributes=true \
    --join-style-attributes=all --apply-transform-to-paths=true  \
    --coordinates-precision=5 --properties-precision=5 \
    --transforms-precision=7 --paths-coordinates-precision=7 \
    --multipass --quiet \
    "$input" "$output" 2>/dev/null
fi

if [[ ! -s "$output" ]]; then
  rm "$output"
  exit
fi

output_size=$(stat -c '%s' "$output")

if [[ "$input_size" -lt "$output_size" ]]; then
  rm "$output"
  exit
fi

cat "$output" > "$input"

echo "  -> /$input $(numfmt --to=iec $input_size)/$(numfmt --to=iec $output_size)"

rm "$output"
