#!/usr/bin/env bash

while read line; do
  if [[ -s "$line" ]]; then
    if [[ "$line" = *.jpg || "$line" = *.svg || "$line" = *.png ]]; then
      input=`wc -c $line | cut -d' ' -f1`

      if [[ "$line" == *.png ]]; then
        orig_colors=$(identify -format %k "$line")

        colors=$(awk "BEGIN {print int(${orig_colors}**0.4*10 )}" )

        convert "$line" -colors "${colors}" "$line"
        optipng -strip all -o3 "$line" 2>/dev/null
      fi


      if [[ "$line" = *.jpg ]]; then
        jpegoptim --quiet --strip-all -m30 "$line" 2>/dev/null
      fi

      if [[ "$line" = *.svg ]]; then
        svgcleaner --remove-gradient-attributes=true \
          --join-style-attributes=all --apply-transform-to-paths=true  \
          --coordinates-precision=5 --properties-precision=5 \
          --transforms-precision=7 --paths-coordinates-precision=7 \
          --multipass --quiet \
          "$line" "$line" 2>/dev/null
      fi

      output=`wc -c $line | cut -d' ' -f1`

      echo "  -> /$line $(numfmt --to=si --format="%.1f" $input)/$(numfmt --to=si --format="%.1f" $output)"

    fi
  fi
done
